name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libboost-graph1.71-dev libboost-test1.71-dev -yq
    - name: Run unit tests
      run: make run_tests COVERAGE=1
    - name: Upload coverage data to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true
