name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libboost-all-dev -yq
    - name: Run unit tests
      run: make run_tests
